### ISSUE TITLE
config.json won't generate if username is different from home directory name

### ISSUE THREAD

**Issue by ivabus** [plainDE/plainPanel#10]
# Bug report
Error occurs while generating config.json if username is different from home directory name

# Steps to reproduce
1. Make home folder name != username
2. Install plainPanel
3. Run plainPanel

# Screenshot
On screenshot username is `ivabus` and home directory is `/home/ivabus.linux`
<img width="633" alt="Screenshot" src="https://user-images.githubusercontent.com/71599788/172897322-f55a6370-9a7a-4e5c-b606-8db9a2b51a1d.png">

**Comment by thm-unix** [comment]
Will be fixed in the next release.

**Comment by thm-unix** [comment]
Fixed in 0.2.
