### ISSUE TITLE
Missing version in config.json + Icons issues

### ISSUE THREAD

**Issue by purpleleaf** [plainDE/plainPanel#28]
As in subject, in plainpanel config.json     "configVersion" is missing, and the panel does not start.
Adding this variable fix the problem.

**Comment by thm-unix** [comment]
Hello! Thank you for leaving bug report. Sorry I didn't answer you earlier. Did you update plainDE or got this issue right after installation? Anyways, I'd recommend you to update to 0.5.1, because 0.5 is found to be quite buggy

**Comment by purpleleaf** [comment]
Hello, thanks for your kind answer. 

I'm on an Arch derivative (Artix), and i make a fresh install of plaiPanel from AUR. The version is 5.1.

The package only install plainPanel binary, please let me know if this can be the problem.

**Comment by thm-unix** [comment]
Hello! AUR is currently abandoned (it will be restored in future), so please consider using this command to install plainDE using plainInstaller.
`sh -c "$(curl -fsSL plainde.github.io/install)"`
OR
`git clone https://github.com/plainDE/plainInstaller`
and run `./installer.sh`
[plainInstaller](https://github.com/plainDE/plainInstaller) will install [plainPanel](https://github.com/plainDE/plainPanel), [plainControlCenter](https://github.com/plainDE/plainControlCenter), [plainAbout](https://github.com/plainDE/plainAbout), [plainBase](https://github.com/plainDE/plainBase) and [plainArtwork](https://github.com/plainDE/plainArtwork).

Previously, delete AUR package and all traces of plainDE (/usr/bin/plain*, /usr/share/plainDE and ~/.config/plainDE).
I will close this issue only after getting a report that everything is ok.

Thank you for mentioning this issue.

**Comment by purpleleaf** [comment]
installing with provided command leads to a working applications.
The only problem i can find is the cutted in half usermenu icon.
Issue can be closed.
Many thanks for your work, i hope development of PlainDE will continue; tint2 ha ceased his activity so there is a tremendous need for an new contender in lightweight panel/DE arena ;)

**Comment by thm-unix** [comment]
I guess problem with user icon is related to icon pack. During the development I rely on Mint-Y (& Mint-Y-Legacy) icon pack. But I will create my own icon packs in future.

Development of plainDE will continue, I have many plans for the future :)
Thank you for pointing out this issue with AUR. I hope you will enjoy using plainDE. Best regards.

**Comment by purpleleaf** [comment]
I confirm this. Using Mint-Y icon pack fix the problem

I suggest to find a way to use the icon pack setted in
Settings->Appearance. This simplify the work, set once then forget.
You just have to set as dependencie an iconpack broadly
available in all distribution, then let the users adopt the one they
like.
Furthermore, using symbolic icons the panel will not suffer from
switching to dark background in the panel. At the moment i use dark
background and the battery icon is not well visible.

Il giorno Sat, 06 May 2023 12:27:11 -0700
thm-unix ***@***.***> ha scritto:

> I guess problem with user icon is related to icon pack. During the
> development I rely on Mint-Y (& Mint-Y-Legacy) icon pack. But I will
> create my own icon packs in future.
> 
> Development of plainDE will continue, I have many plans for the
> future :) Thank you for pointing out this issue with AUR. I hope you
> will enjoy using plainDE. Best regards.
>

**Comment by thm-unix** [comment]
Hello. I drew battery icons by myself because there were some problems with using icon pack's battery icons (this is a temporary measure). Please specify which theme you use (gradient-dark, still-dark or solarized-dark). It should choose battery icon taking into account selected theme (look /usr/share/plainDE/icons/).

Talking about an icon pack, initially I used Adwaita icon pack as default. But later I found some disagreements with other icon packs, so switched to Mint-Y which is not available from usual repos in all distros.

**Comment by purpleleaf** [comment]
The battery icon have a strange behaviour.
Just after saving the appearance settings (or just after launching plainPanel) it shows itself like it should be, but after a few seconds it switch its color from dark to white in light themes, and for white to dark in dark themes.
I verified this for all themes.

**Comment by thm-unix** [comment]
Hello. I confirm this bug. Will investigate & fix it in 0.5.2.

**Comment by thm-unix** [comment]
Fixed. Wait for 0.5.2 release (expect approximately in a week)
